### ISSUE TITLE
How to get source branch name?

### ISSUE THREAD

**Issue by oleksandr-bulakaiev-rft** [samcontesse/gitlab-merge-request-resource#35]
I would appreciate a lot if you have any suggestion where to grab merge request source branch name from in order to use in the task.

**Comment by samcontesse** [comment]
Hi Oleksandr,
Did you find a way to achieve what you want? The `in` script dumps the GitLab merge request in a file called `.git/merge-request.json`. You should be able to use `jq` (or some other json friendly tool) to extract the source branch name from your task.

**Comment by dschulten** [comment]
@samcontesse Since the source branch name is probably something which many builds would like to know, would it be possible to write a file containing the source branch into the merge-request folder, sth like *merge-request/source-branch* (maybe make the file path configurable, like the semver resource does)?

Workaround:
The following assigns the source branch to $SOURCE_BRANCH without installing additional tools (in alpine-based images), invoke from merge-request input folder. 

This is of course a very simple solution that assumes merge-request.json is a one-liner and mostly flat json, so if you have jq at your disposal, absolutely use jq to get rock-solid json parsing. If samcontesse decides to pretty-print merge-request.json, this will break. You have been warned.

Having said that:

```
SOURCE_BRANCH=$(sed 's/,"/\n"/g' .git/merge-request.json | awk 'BEGIN { FS=":"; } /\"source_branch\"/ { gsub(/"/, "", $2); print $2; }')
```

* sed replaces ," by \n" - now it's not json anymore, but lines of key-values, ready for awk
* awk splits the lines by : and then filters them by "source_branch", finally the gsub command removes the double quotes from the found value

**Comment by xela30** [comment]
> Hi Oleksandr, Did you find a way to achieve what you want? The `in` script dumps the GitLab merge request in a file called `.git/merge-request.json`. You should be able to use `jq` (or some other json friendly tool) to extract the source branch name from your task.

Hi @samcontesse . Yup, that's what I did. Thanks.

**Comment by samcontesse** [comment]
The source branch name is now exported. Check the README.
