### ISSUE TITLE
Committer identity unknown

### ISSUE THREAD

**Issue by TommyStarK** [samcontesse/gitlab-merge-request-resource#98]
Hi  😃 ,

Since today I am having issue with pipelines triggered by merge requests. 

![Screenshot 2022-10-12 at 17 58 53](https://user-images.githubusercontent.com/9576370/195392224-f45d63bd-3189-40a9-bf5c-018fe43c6917.png)

Updating the pipeline description and enforcing tag `v0.1.3` when declaring the gitlab merge request resource solves the issue.

Our Concourse pipelines run since two years and there was no configuration update so I assume that it could come from today's release. 

hope this can be of any help.

Best,

**Comment by samcontesse** [comment]
@ericb-summit can you have a look please?

**Comment by ericb-summit** [comment]
@samcontesse will do, but I actually never figured out the source of this issue.  Instead, I have a PR to set a dummy committer identity.

I'll prepare the PR, and at the same time see if can diagnose the cause for this.

**Comment by TommyStarK** [comment]
If you need more info about the context of our pipeline feel free to ask. 
Setting a dummy identity should definitely solve the issue, the aim of this step is to determine the single revision that will be the target for this pipeline. 
Just so you know we have run thousands of pipelines and never face this issue before yesterday. 

Best

**Comment by ericb-summit** [comment]
No that's fine.  So yeah I put back my debugging code and the failure is, as before, at the merge step.

![image](https://user-images.githubusercontent.com/75135427/195598752-43a0b55d-3de1-4e4d-a8e4-d70c2a913e16.png)

In other words, it's git merge itself that tells me where to go.  So I dumb this down to the max and run it in a virgin alpine.

```
12:49 $ docker run --rm -it alpine
/ # apk add --update git > /dev/null
/ # git clone -v -c http.sslVerify=false -o target -b develop https://gitlab-ci-token:xxxxx@gitlab.summit-tech.org/bin/test-service.git /tmp/build/get
Cloning into '/tmp/build/get'...
POST git-upload-pack (359 bytes)
POST git-upload-pack (252 bytes)
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 55 (delta 13), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (55/55), 38.89 KiB | 2.78 MiB/s, done.
Resolving deltas: 100% (13/13), done.
/ # cd /tmp/build/get/
/tmp/build/get # git remote add source https://gitlab-ci-token:xxxxx@gitlab.summit-tech.org/bin/test-service.git
/tmp/build/get # git merge -v --no-ff --no-commit ce2f8c7da8425363013dcdb21d53f6ae4dbe0341
Committer identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@04aa96e60677.(none)')
/tmp/build/get #
```

So this behaviour is not something that we could have broken recently because bone stock alpine:latest, fed the same commands, behaves identically.  Logic says, you're telling git `--no-ff` `--no-commit` so there should be no commit.  And if I give it a dummy identity and run the merge, there is no actually commit.  So if I had to guess, bug in newer git version?  A quick STFW doesn't reap any useful results.

I would not change how the MR is checked out, since the way @samcontesse does it is in line what gitlab itself tells you to do on page of any MR.  I would simply consider adding a dummy committer identity to placate git.  See #99

**Comment by samcontesse** [comment]
@ericb-summit good catch — this bug was probably introduced when we switched to alpine. I would like to avoid having new options when not necessary. I proposed an [alternate way](https://github.com/samcontesse/gitlab-merge-request-resource/pull/100) to initialise the author with the user currently authenticated on GitLab, let me know if you think it is ok.

**Comment by ericb-summit** [comment]
@TommyStarK try release 1.5 it should fix the issue

**Comment by TommyStarK** [comment]
Will do. Thanks to both of you.

**Comment by TommyStarK** [comment]
Working fine 😃
